---
version: 1
kind: application
meta:
  name: 'react-es2018:1'
  brief: S3 hosted React frontend application
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/app-templates
    dir: .
    branch: APPLICATIONS_TAG
    fromEnv: GITHUB_TOKEN

requires:
  - kubernetes

components: []

parameters:
  - name: application.name
    value: react-app-next
  - name: application.description
    value: React application
  - name: application.namespace
    value: cool
  - name: application.replicas
    value: 1
  - name: application.version
    value: latest
  - name: application.state.file
    fromEnv: APP_STATE_FILE
  - name: application.protocol
    value: http
  - name: application.ingress.host
    value: '${component.s3website.name}.${dns.domain}'
  - name: application.bucket
    value: '${component.s3website.bucket}'
  - name: application.theme
  - name: application.pipeline.name
    value: main  
  - name: component.ingress.protocol
  - name: component.ingress.fqdn
  - name: component.git.remote
  - name: component.jenkins.url
  - name: component.s3website.name
    value: ${application.name}
  - name: dns.domain
    env: DOMAIN_NAME
  - name: cloud.region
  - name: terraform.bucket
    parameters:
    - name: name
    - name: region

outputs:
  - name: application.git.remote
    value: '${component.git.remote}'
  - name: application.name
    value: '${application.name}'
  - name: application.namespace
    value: '${application.namespace}'
  - name: application.theme
  - name: application.fqdn
    value: '${application.ingress.host}'
  - name: application.path
    value: '${component.s3website.path}'
  - name: application.url
    value: '${application.protocol}://${application.ingress.host}/${application.path}'
  - name: application.bucket
    value: '${component.s3website.bucket}'
  - name: application.jenkins.pipeline.url
    value: '${component.jenkins.url}/job/${application.name}/job/${application.pipeline.name}-${application.name}'

templates:
  files:
    - templates/*.template
