---
components:
- name: s3
  source:
    repoUrl: https://github.com/agilestacks/components.git
    repoPath: applications/components/s3-website
    dir: components/s3-website
    branch: COMPONENTS_TAG
    fromEnv: GITHUB_TOKEN

lifecycle:
  bare: allow
  verbs: [deploy, undeploy]
  order:
    - s3

parameters:
- name: component.s3website
  parameters:
  - name: name
  - name: baseDomain
    value: ${dns.domain}
  - name: bucket
  - name: endpoint

outputs:
- name: application.bucket
  value: ${component.s3website.bucket}
- name: application.endpoint
  value: ${component.s3website.endpoint}
